#!/usr/bin/env ruby

require_relative 'lib/environment'
Environment.environment = ENV["DB"] || "development"

require_relative 'lib/router'

def clean_gets
  (gets || "").chomp
end

puts IO.readlines('votetracker.txt')

start_menu_controller = StartMenuController.new()
start_menu_controller.list
